// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using Newtonsoft.Json;
using System.Net;
using nsxtsdk;
using nsxtsdk.Models;
using nsxtsdk.ManagerModels;

namespace nsxtapi.ManagerModules
{
    public class NodeAuditLog
    {
        RestClient restClient;
        JsonSerializerSettings defaultSerializationSettings;
        public NodeAuditLog(RestClient Client, JsonSerializerSettings DefaultSerializationSettings)
        {
            restClient = Client;
            defaultSerializationSettings = DefaultSerializationSettings;
        }
        /// <summary>
        /// 
        /// </summary>
        [NSXTProperty(Description: @"")]
        public NSXTAuditLogListResultType CollectAuditLogs(NSXTAuditLogRequestType AuditLogRequest, long? Cursor = null, string? Fields = null, long? PageSize = null)
        {
            if (AuditLogRequest == null) { throw new System.ArgumentNullException("AuditLogRequest cannot be null"); }
            NSXTAuditLogListResultType returnValue = default(NSXTAuditLogListResultType);
            StringBuilder CollectAuditLogsServiceURL = new StringBuilder("/administration/audit-logs");
            var request = new RestRequest
            {              
                RequestFormat = DataFormat.Json,
                Method = Method.POST
            };
            request.AddHeader("Content-type", "application/json");
            request.AddJsonBody(JsonConvert.SerializeObject(AuditLogRequest, defaultSerializationSettings));
            if (Cursor != null) { request.AddQueryParameter("cursor", Cursor.ToString()); }
            if (Fields != null) { request.AddQueryParameter("fields", Fields.ToString()); }
            if (PageSize != null) { request.AddQueryParameter("page_size", PageSize.ToString()); }
            request.Resource = CollectAuditLogsServiceURL.ToString();
            var response = restClient.Execute(request);
            if (response.StatusCode == HttpStatusCode.OK)
			{
                returnValue = JsonConvert.DeserializeObject<NSXTAuditLogListResultType>(response.Content, defaultSerializationSettings);
			}
            else
            {
                throw new NSXTException(response.Content, response.StatusCode.ToString());
            }
            return returnValue;
        }
        /// <summary>
        /// 
        /// </summary>
        [NSXTProperty(Description: @"")]
        public NSXTAlarmListResultType CollectAlarms(long? Cursor = null, string? Fields = null, long? PageSize = null)
        {
            NSXTAlarmListResultType returnValue = default(NSXTAlarmListResultType);
            StringBuilder CollectAlarmsServiceURL = new StringBuilder("/hpm/alarms");
            var request = new RestRequest
            {              
                RequestFormat = DataFormat.Json,
                Method = Method.GET
            };
            request.AddHeader("Content-type", "application/json");
            if (Cursor != null) { request.AddQueryParameter("cursor", Cursor.ToString()); }
            if (Fields != null) { request.AddQueryParameter("fields", Fields.ToString()); }
            if (PageSize != null) { request.AddQueryParameter("page_size", PageSize.ToString()); }
            request.Resource = CollectAlarmsServiceURL.ToString();
            var response = restClient.Execute(request);
            if (response.StatusCode == HttpStatusCode.OK)
			{
                returnValue = JsonConvert.DeserializeObject<NSXTAlarmListResultType>(response.Content, defaultSerializationSettings);
			}
            else
            {
                throw new NSXTException(response.Content, response.StatusCode.ToString());
            }
            return returnValue;
        }
    }
}
