// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Operator of the scope expression eg- tag.scope = &quot;S1&quot;.
    /// </summary>
    [NSXTProperty(Description: @"Operator of the scope expression eg- tag.scope = &quot;S1&quot;.")]
    public enum NSXTNsgroupTagExpressionScopeOpEnumType
    {
        [EnumMember(Value = "EQUALS")]
        EQUALS = 1,
    }
}
