// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Indicates the controller node&apos;s MP channel connectivity status
    /// </summary>
    [NSXTProperty(Description: @"Indicates the controller node&apos;s MP channel connectivity status")]
    public enum NSXTMgmtConnStatusConnectivityStatusEnumType
    {
        [EnumMember(Value = "CONNECTED")]
        CONNECTED = 1,
        [EnumMember(Value = "DISCONNECTED")]
        DISCONNECTED = 2,
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 3,
    }
}
