// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// The resource_type property identifies persistence profile type.
    /// </summary>
    [NSXTProperty(Description: @"The resource_type property identifies persistence profile type.")]
    public enum NSXTLbPersistenceProfileResourceTypeEnumType
    {
        [EnumMember(Value = "LBCOOKIEPERSISTENCEPROFILE")]
        LbCookiePersistenceProfile = 1,
        [EnumMember(Value = "LBSOURCEIPPERSISTENCEPROFILE")]
        LbSourceIpPersistenceProfile = 2,
        [EnumMember(Value = "LBGENERICPERSISTENCEPROFILE")]
        LbGenericPersistenceProfile = 3,
    }
}
