// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// If this property is unset, this session will be treated asLocalPortMirrorSession.
    /// </summary>
    [NSXTProperty(Description: @"If this property is unset, this session will be treated asLocalPortMirrorSession.")]
    public enum NSXTPortMirroringSessionSessionTypeEnumType
    {
        [EnumMember(Value = "LOGICALPORTMIRRORSESSION")]
        LogicalPortMirrorSession = 1,
        [EnumMember(Value = "UPLINKPORTMIRRORSESSION")]
        UplinkPortMirrorSession = 2,
        [EnumMember(Value = "RSPANSRCMIRRORSESSION")]
        RspanSrcMirrorSession = 3,
        [EnumMember(Value = "RSPANDSTMIRRORSESSION")]
        RspanDstMirrorSession = 4,
        [EnumMember(Value = "LOCALPORTMIRRORSESSION")]
        LocalPortMirrorSession = 0,
        [EnumMember(Value = "LOGICALLOCALPORTMIRRORSESSION")]
        LogicalLocalPortMirrorSession = 1,
        [EnumMember(Value = "L3PORTMIRRORSESSION")]
        L3PortMirrorSession = 2,
    }
}
