// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Type of the NSServiceGroup
    /// </summary>
    [NSXTProperty(Description: @"Type of the NSServiceGroup")]
    public enum NSXTNsserviceGroupServiceTypeEnumType
    {
        [EnumMember(Value = "ETHER")]
        ETHER = 1,
        [EnumMember(Value = "NON_ETHER")]
        NONETHER = 2,
    }
}
