// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Address family for Route Redistribution
    /// </summary>
    [NSXTProperty(Description: @"Address family for Route Redistribution")]
    public enum NSXTRedistributionRuleAddressFamilyEnumType
    {
        [EnumMember(Value = "IPV4")]
        IPV4 = 1,
        [EnumMember(Value = "IPV6")]
        IPV6 = 2,
        [EnumMember(Value = "IPV4_AND_IPV6")]
        IPV4ANDIPV6 = 0,
    }
}
