// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// The type of System Health Agent plugin
    /// </summary>
    [NSXTProperty(Description: @"The type of System Health Agent plugin")]
    public enum NSXTSystemHealthPluginProfileTypeEnumType
    {
        [EnumMember(Value = "COMPUTE")]
        COMPUTE = 1,
        [EnumMember(Value = "STORAGE")]
        STORAGE = 2,
        [EnumMember(Value = "NETWORK")]
        NETWORK = 0,
        [EnumMember(Value = "HYPERBUS")]
        HYPERBUS = 1,
        [EnumMember(Value = "NCP")]
        NCP = 2,
        [EnumMember(Value = "NODEAGENT")]
        NODEAGENT = 3,
        [EnumMember(Value = "VSAN")]
        VSAN = 4,
        [EnumMember(Value = "TNAGENT")]
        TNAGENT = 5,
        [EnumMember(Value = "UPLINK")]
        UPLINK = 6,
    }
}
