// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// DAD Mode
    /// </summary>
    [NSXTProperty(Description: @"DAD Mode")]
    public enum NSXTDadprofileDadModeEnumType
    {
        [EnumMember(Value = "LOOSE")]
        LOOSE = 1,
        [EnumMember(Value = "STRICT")]
        STRICT = 2,
    }
}
