// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTUpgradeCheckListResultType : NSXTListResultType
    {
        /// <summary>
        /// Paged Collection of pre/post-upgrade checks
        /// </summary>
        [JsonProperty(PropertyName = "checks", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Paged Collection of pre/post-upgrade checks")]
        [System.ComponentModel.DataAnnotations.Required]
        public IList<NSXTUpgradeCheckType> Checks { get; set; }
    }
}
