// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// BGP Graceful Restart configuration parameters
    /// </summary>
    [NSXTProperty(Description: @"BGP Graceful Restart configuration parameters")]
    public class NSXTGracefulRestartConfigType 
    {
        /// <summary>
        /// BGP Graceful Restart mode
        /// </summary>
        public NSXTGracefulRestartConfigGracefulRestartModeEnumType? GracefulRestartMode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTGracefulRestartTimerType GracefulRestartTimer { get; set; }
    }
}
