// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTLogicalRouterLinkPortOnTIER0Type : NSXTLogicalRouterPortType
    {
        /// <summary>
        /// Logical router port subnets
        /// </summary>
        public IList<NSXTIPSubnetType> Subnets { get; set; }
        /// <summary>
        /// Identifier of connected LogicalRouterLinkPortOnTIER1 of TIER1 logical router
        /// </summary>
        public string? LinkedLogicalRouterPortId { get; set; }
        /// <summary>
        /// MAC address
        /// </summary>
        public string? MacAddress { get; set; }
    }
}
