// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Properties that affect the configuration of the NSX API service.
    /// </summary>
    [NSXTProperty(Description: @"Properties that affect the configuration of the NSX API service.")]
    public class NSXTApiServiceConfigType 
    {
        /// <summary>
        /// The maximum number of concurrent API requests that will be serviced. If the number of API requests being processed
        /// exceeds this limit, new API requests will be refused and a 503 Service Unavailable response will be returned to the
        /// client.  To disable API concurrency limiting, set this value to 0.
        /// </summary>
        public long? GlobalApiConcurrencyLimit { get; set; }
        /// <summary>
        /// The list of IP addresses which are not subjected to a lockout on failed login attempts.
        /// </summary>
        public IList<string> LockoutImmuneAddresses { get; set; }
        /// <summary>
        /// Identifies whether basic authentication is enabled or disabled in API calls.
        /// </summary>
        public bool? BasicAuthenticationEnabled { get; set; }
        /// <summary>
        /// Host name or IP address to use for redirect location headers, or empty string to derive from current request. To
        /// disable, set redirect_host to the empty string ("").
        /// </summary>
        public string? RedirectHost { get; set; }
        /// <summary>
        /// The TLS cipher suites that the API service will negotiate.
        /// </summary>
        public IList<NSXTCipherSuiteType> CipherSuites { get; set; }
        /// <summary>
        /// Identifies whether cookie-based authentication is enabled or disabled in API calls. When cookie-based authentication is
        /// disabled, new sessions cannot be created via /api/session/create.
        /// </summary>
        public bool? CookieBasedAuthenticationEnabled { get; set; }
        /// <summary>
        /// NSX session inactivity timeout
        /// </summary>
        public long? SessionTimeout { get; set; }
        /// <summary>
        /// The maximum number of API requests that will be serviced per second for a given authenticated client.  If more API
        /// requests are received than can be serviced, a 429 Too Many Requests HTTP response will be returned. To disable API rate
        /// limiting, set this value to 0.
        /// </summary>
        public long? ClientApiRateLimit { get; set; }
        /// <summary>
        /// The maximum number of concurrent API requests that will be serviced for a given authenticated client.  If the number of
        /// API requests being processed exceeds this limit, new API requests will be refused and a 503 Service Unavailable response
        /// will be returned to the client. To disable API concurrency limiting, set this value to 0.
        /// </summary>
        public long? ClientApiConcurrencyLimit { get; set; }
        /// <summary>
        /// The TLS protocol versions that the API service will negotiate.
        /// </summary>
        public IList<NSXTProtocolVersionType> ProtocolVersions { get; set; }
        /// <summary>
        /// NSX connection timeout, in seconds. To disable timeout, set to 0.
        /// </summary>
        public long? ConnectionTimeout { get; set; }
    }
}
