// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTLbVirtualServerStatisticsListResultType : NSXTListResultType
    {
        public NSXTLbVirtualServerStatisticsListResultType()
        {
        }
        /// <summary>
        /// paginated statistics list of virtual servers
        /// </summary>
        [JsonProperty(PropertyName = "results", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"paginated statistics list of virtual servers")]
        [System.ComponentModel.DataAnnotations.Required]
        public IList<NSXTLbVirtualServerStatisticsType> Results { get; set; }
    }
}
