// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTHttpsProtocolType : NSXTProtocolType
    {
        /// <summary>
        /// SSL thumbprint of server
        /// </summary>
        [JsonProperty(PropertyName = "sha256_thumbprint", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"SSL thumbprint of server")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Sha256Thumbprint { get; set; }
        /// <summary>
        /// Scheme to authenticate if required
        /// </summary>
        [JsonProperty(PropertyName = "authentication_scheme")]
        [NSXTProperty(IsRequired: false, Description: @"Scheme to authenticate if required")]
        public NSXTBasicAuthenticationSchemeType AuthenticationScheme { get; set; }
    }
}
