// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTNSServiceType : NSXTManagedResourceType
    {
        /// <summary>
        /// The default NSServices are created in the system by default. These NSServices
        /// can't be modified/deleted
        /// </summary>
        [JsonProperty(PropertyName = "default_service")]
        [NSXTProperty(IsRequired: false, Description: @"The default NSServices are created in the system by default. These NSServicescan&apos;t be modified/deleted")]
        public bool? DefaultService { get; set; }
        /// <summary>
        /// An NSService Element that describes traffic corresponding to this NSService
        /// </summary>
        [JsonProperty(PropertyName = "nsservice_element", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"An NSService Element that describes traffic corresponding to this NSService")]
        [System.ComponentModel.DataAnnotations.Required]
        public NSXTNSServiceElementType NsserviceElement { get; set; }
    }
}
