// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTPortMirroringSessionType : NSXTManagedResourceType
    {
        /// <summary>
        /// Port mirroring session direction
        /// </summary>
        [JsonProperty(PropertyName = "direction", Required = Required.AllowNull)]
        public NSXTPortMirroringSessionDirectionEnumType Direction { get; set; }
        /// <summary>
        /// Mirror sources
        /// </summary>
        [JsonProperty(PropertyName = "mirror_sources", Required = Required.AllowNull)]
        public IList<NSXTMirrorSourceType> MirrorSources { get; set; }
        /// <summary>
        /// Only for Remote SPAN Port Mirror.
        /// </summary>
        public long? EncapsulationVlanId { get; set; }
        /// <summary>
        /// If this property is unset, this session will be treated as
        /// LocalPortMirrorSession.
        /// </summary>
        public NSXTPortMirroringSessionSessionTypeEnumType? SessionType { get; set; }
        /// <summary>
        /// If this property is set, the packet will be truncated to the provided
        /// length. If this property is unset, entire packet will be mirrored.
        /// </summary>
        public long? SnapLength { get; set; }
        /// <summary>
        /// An array of 5-tuples used to filter packets for the mirror session, if not provided, all the packets will be mirrored.
        /// </summary>
        public IList<NSXTPortMirroringFilterType> PortMirroringFilters { get; set; }
        /// <summary>
        /// If set to mirror, mirror packet will be sent via dedicated mirror stack
        /// to destination; If set to default, mirror packet will be sent via default stack;
        /// So far, the value mirror can only be chosen in L3PortMirrorSession.
        /// </summary>
        public NSXTPortMirroringSessionTcpIpStackEnumType? TcpIpStack { get; set; }
        /// <summary>
        /// Only for Remote SPAN Port Mirror. Whether to preserve original VLAN.
        /// </summary>
        public bool? PreserveOriginalVlan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "mirror_destination", Required = Required.AllowNull)]
        public NSXTMirrorDestinationType MirrorDestination { get; set; }
    }
}
