// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Identity Firewall user login/session data for a single user.
    /// </summary>
    [NSXTProperty(Description: @"Identity Firewall user login/session data for a single user.")]
    public class NSXTIdfwUserStatsType 
    {
        /// <summary>
        /// AD user Identifier (String ID)
        /// </summary>
        public string? UserId { get; set; }
        /// <summary>
        /// List of active (still logged in) user login/sessions data (no limit)
        /// </summary>
        [JsonProperty(PropertyName = "active_sessions", Required = Required.AllowNull)]
        public IList<NSXTIdfwUserSessionDataType> ActiveSessions { get; set; }
        /// <summary>
        /// Optional list of up to 5 most recent archived (previously logged in) user
        /// login/session data.
        /// </summary>
        public IList<NSXTIdfwUserSessionDataType> ArchivedSessions { get; set; }
    }
}
