// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTControlClusterNodeStatusType 
    {
        /// <summary>
        /// 
        /// </summary>
        public NSXTMgmtConnStatusType MgmtConnectionStatus { get; set; }
        /// <summary>
        /// Status of this node's connection to the control cluster
        /// </summary>
        public NSXTControlClusterNodeStatusControlClusterStatusEnumType? ControlClusterStatus { get; set; }
    }
}
