// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Authenticated User Info
    /// </summary>
    [NSXTProperty(Description: @"Authenticated User Info")]
    public class NSXTUserInfoType 
    {
        public NSXTUserInfoType()
        {
        }
        /// <summary>
        /// User Name
        /// </summary>
        [JsonProperty(PropertyName = "user_name")]
        [NSXTProperty(IsRequired: false, Description: @"User Name")]
        public string? UserName { get; set; }
        /// <summary>
        /// Permissions
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        [NSXTProperty(IsRequired: false, Description: @"Permissions")]
        public IList<NSXTNsxRoleType> Roles { get; set; }
    }
}
