// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// Base type for CSV records.
    /// </summary>
    [NSXTProperty(Description: @"Base type for CSV records.")]
    public class NSXTCsvRecordType 
    {
        public NSXTCsvRecordType()
        {
        }
    }
}
