// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTLogicalRouterIPTunnelPortType : NSXTLogicalRouterPortType
    {
        /// <summary>
        /// Tunnel port subnets.
        /// </summary>
        [JsonProperty(PropertyName = "subnets")]
        [NSXTProperty(IsRequired: false, Description: @"Tunnel port subnets.")]
        public IList<NSXTIPSubnetType> Subnets { get; set; }
        /// <summary>
        /// Admin state of port.
        /// </summary>
        [JsonProperty(PropertyName = "admin_state")]
        [NSXTProperty(IsRequired: false, Description: @"Admin state of port.")]
        public NSXTLogicalRouterIptunnelPortAdminStateEnumType? AdminState { get; set; }
        /// <summary>
        /// Associated VPN session identifier.
        /// </summary>
        [JsonProperty(PropertyName = "vpn_session_id")]
        [NSXTProperty(IsRequired: false, Description: @"Associated VPN session identifier.")]
        public string? VpnSessionId { get; set; }
    }
}
