// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTManagementClusterStatusType 
    {
        /// <summary>
        /// The current status of the management cluster
        /// </summary>
        public NSXTManagementClusterStatusStatusEnumType? Status { get; set; }
        /// <summary>
        /// Current missing management plane nodes
        /// </summary>
        public IList<NSXTManagementPlaneBaseNodeInfoType> OfflineNodes { get; set; }
        /// <summary>
        /// The details of the cluster nodes required for cluster initialization
        /// </summary>
        public IList<NSXTClusterInitializationNodeInfoType> RequiredMembersForInitialization { get; set; }
        /// <summary>
        /// Current alive management plane nodes
        /// </summary>
        public IList<NSXTManagementPlaneBaseNodeInfoType> OnlineNodes { get; set; }
    }
}
