// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTFirewallRuleType : NSXTDSRuleType
    {
        public NSXTFirewallRuleType()
        {
        }
        /// <summary>
        /// List of the services. Null will be treated as any.
        /// </summary>
        [JsonProperty(PropertyName = "services")]
        [NSXTProperty(IsRequired: false, Description: @"List of the services. Null will be treated as any.")]
        public IList<NSXTFirewallServiceType> Services { get; set; }
        /// <summary>
        /// NS Profile object which accepts attributes and sub-attributes of various network services (ex. L7 AppId, domain name,
        /// encryption algorithm) as key value pairs.
        /// </summary>
        [JsonProperty(PropertyName = "context_profiles")]
        [NSXTProperty(IsRequired: false, Description: @"NS Profile object which accepts attributes and sub-attributes of various network services (ex. L7 AppId, domain name, encryption algorithm) as key value pairs.")]
        public IList<NSXTResourceReferenceType> ContextProfiles { get; set; }
        /// <summary>
        /// List of NSGroups that have end point attributes like AD Groups(SID), process name, process hash etc. For Flash release,
        /// only NSGroups containing AD Groups are supported.
        /// </summary>
        [JsonProperty(PropertyName = "extended_sources")]
        [NSXTProperty(IsRequired: false, Description: @"List of NSGroups that have end point attributes like AD Groups(SID), process name, process hash etc. For Flash release, only NSGroups containing AD Groups are supported.")]
        public IList<NSXTResourceReferenceType> ExtendedSources { get; set; }
        /// <summary>
        /// Section Id of the section to which this rule belongs to.
        /// </summary>
        [JsonProperty(PropertyName = "section_id")]
        [NSXTProperty(IsRequired: false, Description: @"Section Id of the section to which this rule belongs to.")]
        public string? SectionId { get; set; }
    }
}
