// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTIssuerSerialNumberType 
    {
        /// <summary>
        /// List of Certificate Serial Numbers issued by the specified issuers.
        /// </summary>
        public IList<string> SerialNumbers { get; set; }
        /// <summary>
        /// Issuer Distinguished Name of the revoked certificates.
        /// </summary>
        public string? Issuer { get; set; }
    }
}
