// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTComponentTargetVersionType 
    {
        /// <summary>
        /// 
        /// </summary>
        public string? TargetVersion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string? ComponentType { get; set; }
    }
}
