// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.ManagerModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTClusterBackupInfoListResultType : NSXTListResultType
    {
        public NSXTClusterBackupInfoListResultType()
        {
        }
        /// <summary>
        /// List of timestamps of backed-up cluster files
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        [NSXTProperty(IsRequired: false, Description: @"List of timestamps of backed-up cluster files")]
        public IList<NSXTClusterBackupInfoType> Results { get; set; }
    }
}
