// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTALBPoolGroupDeploymentPolicyType : NSXTPolicyConfigResourceType
    {
        /// <summary>
        /// Target traffic ratio before pool is made production.
        /// Allowed values are 1-100.
        /// Unit is RATIO.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as 100.
        /// </summary>
        public long? TargetTestTrafficRatio { get; set; }
        /// <summary>
        /// Duration of evaluation period for automatic deployment.
        /// Allowed values are 60-86400.
        /// Unit is SEC.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as 300.
        /// </summary>
        public long? EvaluationDuration { get; set; }
        /// <summary>
        /// Ratio of the traffic that is sent to the pool under test.
        /// test ratio of 100 means blue green.
        /// Allowed values are 1-100.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as 100.
        /// </summary>
        public long? TestTrafficRatioRampup { get; set; }
        /// <summary>
        /// Placeholder for description of property rules of obj type
        /// PoolGroupDeploymentPolicy field type str  type array.
        /// </summary>
        public IList<NSXTALBPGDeploymentRuleType> Rules { get; set; }
        /// <summary>
        /// It will automatically disable old production pools once
        /// there is a new production candidate.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as true.
        /// </summary>
        public bool? AutoDisableOldProdPools { get; set; }
        /// <summary>
        /// deployment scheme.
        /// Enum options - BLUE_GREEN, CANARY.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as BLUE_GREEN.
        /// </summary>
        public NSXTAlbpoolGroupDeploymentPolicySchemeEnumType? Scheme { get; set; }
        /// <summary>
        /// List of labels to be used for granular RBAC.
        /// Allowed in Basic edition, Essentials edition, Enterprise
        /// edition.
        /// </summary>
        public IList<NSXTALBRoleFilterMatchLabelType> Markers { get; set; }
        /// <summary>
        /// Webhook configured with URL that Avi controller will pass
        /// back information about pool group, old and new pool
        /// information and current deployment rule results.
        /// It is a reference to an object of type Webhook.
        /// </summary>
        public string? WebhookPath { get; set; }
    }
}
