// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTNsxTDnsAnswerType : NSXTPolicyDnsAnswerPerEnforcementPointType
    {
        /// <summary>
        /// Authoritative answers
        /// </summary>
        [JsonProperty(PropertyName = "authoritative_answers")]
        [NSXTProperty(IsRequired: false, Description: @"Authoritative answers")]
        public IList<NSXTNsxTDnsQueryAnswerType> AuthoritativeAnswers { get; set; }
        /// <summary>
        /// ID of the edge node that performed the query.
        /// </summary>
        [JsonProperty(PropertyName = "edge_node_id", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"ID of the edge node that performed the query.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string EdgeNodeId { get; set; }
        /// <summary>
        /// Dns server ip address and port, format is "ip address#port".
        /// </summary>
        [JsonProperty(PropertyName = "dns_server", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Dns server ip address and port, format is &quot;ip address#port&quot;.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string DnsServer { get; set; }
        /// <summary>
        /// Non authoritative answers
        /// </summary>
        [JsonProperty(PropertyName = "non_authoritative_answers")]
        [NSXTProperty(IsRequired: false, Description: @"Non authoritative answers")]
        public IList<NSXTNsxTDnsQueryAnswerType> NonAuthoritativeAnswers { get; set; }
        /// <summary>
        /// It can be NXDOMAIN or error message which is not consisted of
        /// authoritative_answer or non_authoritative_answer.
        /// </summary>
        [JsonProperty(PropertyName = "raw_answer")]
        [NSXTProperty(IsRequired: false, Description: @"It can be NXDOMAIN or error message which is not consisted ofauthoritative_answer or non_authoritative_answer.")]
        public string? RawAnswer { get; set; }
    }
}
