// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Dropdown item definition
    /// </summary>
    [NSXTProperty(Description: @"Dropdown item definition")]
    public class NSXTDropdownItemType 
    {
        /// <summary>
        /// An expression that represents the items of the dropdown filter.
        /// </summary>
        [JsonProperty(PropertyName = "field", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"An expression that represents the items of the dropdown filter.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Field { get; set; }
        /// <summary>
        /// expression to extract display name to be shown in the drop down.
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        [NSXTProperty(IsRequired: false, Description: @"expression to extract display name to be shown in the drop down.")]
        public string? DisplayName { get; set; }
        /// <summary>
        /// Value of filter inside dropdown filter.
        /// </summary>
        [JsonProperty(PropertyName = "value", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Value of filter inside dropdown filter.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Value { get; set; }
    }
}
