// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer ErrorPage object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer ErrorPage object")]
    public class NSXTALBErrorPageType 
    {
        /// <summary>
        /// Index of the error page.
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        [NSXTProperty(IsRequired: false, Description: @"Index of the error page.")]
        public long? Index { get; set; }
        /// <summary>
        /// Custom error page body used to sent to the client.
        /// It is a reference to an object of type ErrorPageBody.
        /// </summary>
        [JsonProperty(PropertyName = "error_page_body_path")]
        [NSXTProperty(IsRequired: false, Description: @"Custom error page body used to sent to the client.It is a reference to an object of type ErrorPageBody.")]
        public string? ErrorPageBodyPath { get; set; }
        /// <summary>
        /// Enable or disable the error page.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as true.
        /// </summary>
        [JsonProperty(PropertyName = "enable")]
        [NSXTProperty(IsRequired: false, Description: @"Enable or disable the error page.Default value when not specified in API or module isinterpreted by ALB Controller as true.")]
        [NSXTDefaultProperty(Default: "")]
        public bool? Enable { get; set; }
        /// <summary>
        /// Add match criteria for http status codes to the error page.
        /// </summary>
        [JsonProperty(PropertyName = "match")]
        [NSXTProperty(IsRequired: false, Description: @"Add match criteria for http status codes to the error page.")]
        public NSXTALBHTTPStatusMatchType Match { get; set; }
        /// <summary>
        /// Redirect sent to client when match.
        /// </summary>
        [JsonProperty(PropertyName = "error_redirect")]
        [NSXTProperty(IsRequired: false, Description: @"Redirect sent to client when match.")]
        public string? ErrorRedirect { get; set; }
    }
}
