// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTRaDNSConfigType 
    {
        /// <summary>
        /// Lifetime of Domain names in milliseconds
        /// </summary>
        public long? DomainNameLifetime { get; set; }
        /// <summary>
        /// DNS server.
        /// </summary>
        public IList<string> DnsServer { get; set; }
        /// <summary>
        /// Domain name in RA message.
        /// </summary>
        public IList<string> DomainName { get; set; }
        /// <summary>
        /// Lifetime of DNS server in milliseconds
        /// </summary>
        public long? DnsServerLifetime { get; set; }
    }
}
