// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Vrf Route Targets for import/export.
    /// </summary>
    [NSXTProperty(Description: @"Vrf Route Targets for import/export.")]
    public class NSXTVrfRouteTargetsType 
    {
        /// <summary>
        /// Address family.
        /// </summary>
        [JsonProperty(PropertyName = "address_family")]
        [NSXTProperty(IsRequired: false, Description: @"Address family.")]
        [NSXTDefaultProperty(Default: "L2VPN_EVPN")]
        public NSXTVrfRouteTargetsAddressFamilyEnumType? AddressFamily { get; set; }
        /// <summary>
        /// Import route targets with format in ASN:<number>.
        /// </summary>
        [JsonProperty(PropertyName = "import_route_targets")]
        [NSXTProperty(IsRequired: false, Description: @"Import route targets with format in ASN:&lt;number&gt;.")]
        public IList<string> ImportRouteTargets { get; set; }
        /// <summary>
        /// Export route targets with format in ASN:<number>.
        /// </summary>
        [JsonProperty(PropertyName = "export_route_targets")]
        [NSXTProperty(IsRequired: false, Description: @"Export route targets with format in ASN:&lt;number&gt;.")]
        public IList<string> ExportRouteTargets { get; set; }
    }
}
