// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Bundle Id for uploaded file.
    /// </summary>
    [NSXTProperty(Description: @"Bundle Id for uploaded file.")]
    public class NSXTUploadBundleIdType 
    {
        public NSXTUploadBundleIdType()
        {
        }
        /// <summary>
        /// Bundle id of uploaded file.
        /// </summary>
        [JsonProperty(PropertyName = "bundle_id")]
        [NSXTProperty(IsRequired: false, Description: @"Bundle id of uploaded file.")]
        public string? BundleId { get; set; }
    }
}
