// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Forwarding Rule statistics for a specfic enforcement point.
    /// </summary>
    [NSXTProperty(Description: @"Forwarding Rule statistics for a specfic enforcement point.")]
    public class NSXTForwardingRuleStatisticsForEnforcementPointType 
    {
        public NSXTForwardingRuleStatisticsForEnforcementPointType()
        {
        }
        /// <summary>
        /// Path for a specific enforcement point
        /// </summary>
        [JsonProperty(PropertyName = "enforcement_point")]
        [NSXTProperty(IsRequired: false, Description: @"Path for a specific enforcement point")]
        public string? EnforcementPoint { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "statistics")]
        [NSXTProperty(IsRequired: false, Description: @"")]
        public NSXTForwardingRuleStatsType Statistics { get; set; }
    }
}
