// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer NetworkProfileUnion object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer NetworkProfileUnion object")]
    public class NSXTALBNetworkProfileUnionType 
    {
        /// <summary>
        /// Configure one of either proxy or fast path profiles.
        /// Enum options - PROTOCOL_TYPE_TCP_PROXY,
        /// PROTOCOL_TYPE_TCP_FAST_PATH, PROTOCOL_TYPE_UDP_FAST_PATH,
        /// PROTOCOL_TYPE_UDP_PROXY.
        /// Allowed in Basic(Allowed values-
        /// PROTOCOL_TYPE_TCP_PROXY,PROTOCOL_TYPE_TCP_FAST_PATH,PROTOCOL_TYPE_UDP_FAST_PATH)
        /// edition, Essentials(Allowed values-
        /// PROTOCOL_TYPE_TCP_FAST_PATH,PROTOCOL_TYPE_UDP_FAST_PATH)
        /// edition, Enterprise edition.
        /// Default value when not specified in API or module is
        /// interpreted by ALB Controller as PROTOCOL_TYPE_TCP_PROXY.
        /// </summary>
        [JsonProperty(PropertyName = "type", Required = Required.AllowNull)]
        public NSXTAlbnetworkProfileUnionTypeEnumType Type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBTCPProxyProfileType TcpProxyProfile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBTCPFastPathProfileType TcpFastPathProfile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBUDPProxyProfileType UdpProxyProfile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBUDPFastPathProfileType UdpFastPathProfile { get; set; }
    }
}
