// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Contains the details of resource field
    /// </summary>
    [NSXTProperty(Description: @"Contains the details of resource field")]
    public class NSXTPolicyFineTuningResourceInfoDetailType 
    {
        /// <summary>
        /// It will represent resource with name and fields.
        /// </summary>
        [JsonProperty(PropertyName = "field_name", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"It will represent resource with name and fields.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string FieldName { get; set; }
        /// <summary>
        /// List of all field of any resource
        /// </summary>
        [JsonProperty(PropertyName = "sub_type", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"List of all field of any resource")]
        [System.ComponentModel.DataAnnotations.Required]
        public NSXTPolicyFineTuningResourceInfoType SubType { get; set; }
    }
}
