// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTVniPoolConfigType : NSXTPolicyConfigResourceType
    {
        public NSXTVniPoolConfigType()
        {
        }
        /// <summary>
        /// Start value of VNI Pool range
        /// </summary>
        [JsonProperty(PropertyName = "start", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Start value of VNI Pool range")]
        //[System.ComponentModel.DataAnnotations.MinLength(75001)]
        //[System.ComponentModel.DataAnnotations.MaxLength(16777215)]
        [System.ComponentModel.DataAnnotations.Required]
        public int Start { get; set; }
        /// <summary>
        /// End value of VNI Pool range
        /// </summary>
        [JsonProperty(PropertyName = "end", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"End value of VNI Pool range")]
        //[System.ComponentModel.DataAnnotations.MinLength(75001)]
        //[System.ComponentModel.DataAnnotations.MaxLength(16777215)]
        [System.ComponentModel.DataAnnotations.Required]
        public int End { get; set; }
    }
}
