// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTOspfStatusInfoType 
    {
        /// <summary>
        /// Retransmit request counter.
        /// </summary>
        public long? RetransmitCounter { get; set; }
        /// <summary>
        /// request counter.
        /// </summary>
        public long? RequestCounter { get; set; }
        /// <summary>
        /// OSPF neighbor state.
        /// </summary>
        public string? State { get; set; }
        /// <summary>
        /// Tier0 interface name.
        /// </summary>
        public string? InterfaceName { get; set; }
        /// <summary>
        /// Time remaining in before considering OSPF neighbor dead.
        /// </summary>
        public string? DeadTime { get; set; }
        /// <summary>
        /// Multicast source address.
        /// </summary>
        public string? SourceAddress { get; set; }
        /// <summary>
        /// Database summary counter.
        /// </summary>
        public long? DatabaseSummaryCounter { get; set; }
        /// <summary>
        /// Time since last change in state.
        /// </summary>
        public string? LastStateChange { get; set; }
        /// <summary>
        /// Priority of the neighbor.
        /// </summary>
        public long? Priority { get; set; }
    }
}
