// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer HTTPSecurityActionRateProfile object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer HTTPSecurityActionRateProfile object")]
    public class NSXTALBHTTPSecurityActionRateProfileType 
    {
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "action", Required = Required.AllowNull)]
        public NSXTALBRateLimiterActionType Action { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "rate_limiter", Required = Required.AllowNull)]
        public NSXTALBRateLimiterType RateLimiter { get; set; }
        /// <summary>
        /// Rate limiting should be done on a per request uri path
        /// basis.
        /// </summary>
        public bool? PerUriPath { get; set; }
        /// <summary>
        /// Rate limiting should be done on a per client ip basis.
        /// </summary>
        public bool? PerClientIp { get; set; }
    }
}
