// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTDistributedVirtualSwitchType : NSXTVirtualSwitchType
    {
        /// <summary>
        /// Array of discovered nodes connected to this switch.
        /// </summary>
        public IList<NSXTDiscoveredNodeType> DiscoveredNodes { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTDistributedVirtualPortgroupType UplinkPortgroup { get; set; }
        /// <summary>
        /// UUID of the switch
        /// </summary>
        public string? Uuid { get; set; }
        /// <summary>
        /// Key-Value map of additional properties of switch
        /// </summary>
        public IList<NSXTKeyValuePairType> OriginProperties { get; set; }
        /// <summary>
        /// It contains information about VMware specific multiple dynamic
        /// LACP groups.
        /// </summary>
        public IList<NSXTLacpGroupConfigInfoType> LacpGroupConfigs { get; set; }
        /// <summary>
        /// The uniform name of uplink ports on each host.
        /// </summary>
        public IList<string> UplinkPortNames { get; set; }
    }
}
