// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Contains up-to-date information relating to an auto-deployed VM, including
        /// its status and (potentially) an error message.
    /// </summary>
    [NSXTProperty(Description: @"Contains up-to-date information relating to an auto-deployed VM, includingits status and (potentially) an error message.")]
    public class NSXTALBControllerNodeVMDeploymentStatusReportType 
    {
        /// <summary>
        /// Status of the addition or deletion of an auto-deployed Advanced Load Balancer controller node VM.
        /// </summary>
        [JsonProperty(PropertyName = "status", Required = Required.AllowNull)]
        public NSXTAlbcontrollerNodeVmdeploymentStatusReportStatusEnumType Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBControllerNodeVMDeploymentProgressStateType DeploymentProgressState { get; set; }
        /// <summary>
        /// In case of auto-deployment-related failure, an error message will be
        /// stored here.
        /// </summary>
        public string? FailureMessage { get; set; }
        /// <summary>
        /// In case of auto-deployment-related failure, the code for the error will
        /// be stored here.
        /// </summary>
        public long? FailureCode { get; set; }
    }
}
