// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTInfraType : NSXTAbstractSpaceType
    {
        public NSXTInfraType()
        {
        }
        /// <summary>
        /// This field is used while creating or updating the infra space.
        /// </summary>
        [JsonProperty(PropertyName = "domains")]
        [NSXTProperty(IsRequired: false, Description: @"This field is used while creating or updating the infra space.")]
        public IList<NSXTDomainType> Domains { get; set; }
    }
}
