// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTTransportProtocolHeaderType 
    {
        /// <summary>
        /// UDP header
        /// </summary>
        [JsonProperty(PropertyName = "udp_header")]
        [NSXTProperty(IsRequired: false, Description: @"UDP header")]
        public NSXTUdpHeaderType UdpHeader { get; set; }
        /// <summary>
        /// DHCP header
        /// </summary>
        [JsonProperty(PropertyName = "dhcp_header")]
        [NSXTProperty(IsRequired: false, Description: @"DHCP header")]
        public NSXTDhcpHeaderType DhcpHeader { get; set; }
        /// <summary>
        /// TCP header
        /// </summary>
        [JsonProperty(PropertyName = "tcp_header")]
        [NSXTProperty(IsRequired: false, Description: @"TCP header")]
        public NSXTTcpHeaderType TcpHeader { get; set; }
        /// <summary>
        /// ICMP echo request header
        /// </summary>
        [JsonProperty(PropertyName = "icmp_echo_request_header")]
        [NSXTProperty(IsRequired: false, Description: @"ICMP echo request header")]
        public NSXTIcmpEchoRequestHeaderType IcmpEchoRequestHeader { get; set; }
        /// <summary>
        /// DHCP v6 header
        /// </summary>
        [JsonProperty(PropertyName = "dhcpv6_header")]
        [NSXTProperty(IsRequired: false, Description: @"DHCP v6 header")]
        public NSXTDhcpv6HeaderType Dhcpv6Header { get; set; }
        /// <summary>
        /// Neighbor discovery protocol header
        /// </summary>
        [JsonProperty(PropertyName = "ndp_header")]
        [NSXTProperty(IsRequired: false, Description: @"Neighbor discovery protocol header")]
        public NSXTNdpHeaderType NdpHeader { get; set; }
        /// <summary>
        /// DNS header
        /// </summary>
        [JsonProperty(PropertyName = "dns_header")]
        [NSXTProperty(IsRequired: false, Description: @"DNS header")]
        public NSXTDnsHeaderType DnsHeader { get; set; }
    }
}
