// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer HealthMonitorAuthInfo object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer HealthMonitorAuthInfo object")]
    public class NSXTALBHealthMonitorAuthInfoType 
    {
        /// <summary>
        /// Username for server authentication.
        /// </summary>
        [JsonProperty(PropertyName = "username", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Username for server authentication.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Username { get; set; }
        /// <summary>
        /// Password for server authentication.
        /// </summary>
        [JsonProperty(PropertyName = "password", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Password for server authentication.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Password { get; set; }
    }
}
