// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTALBWafCRSType : NSXTPolicyConfigResourceType
    {
        public NSXTALBWafCRSType()
        {
        }
        /// <summary>
        /// The release date of this version in RFC 3339 / ISO 8601
        /// format.
        /// </summary>
        [JsonProperty(PropertyName = "release_date", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"The release date of this version in RFC 3339 / ISO 8601format.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string ReleaseDate { get; set; }
        /// <summary>
        /// The version of this ruleset object.
        /// </summary>
        [JsonProperty(PropertyName = "version", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"The version of this ruleset object.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Version { get; set; }
        /// <summary>
        /// Integrity protection value.
        /// </summary>
        [JsonProperty(PropertyName = "integrity", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Integrity protection value.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string Integrity { get; set; }
        /// <summary>
        /// List of labels to be used for granular RBAC.
        /// Allowed in Basic edition, Essentials edition, Enterprise
        /// edition.
        /// </summary>
        [JsonProperty(PropertyName = "markers")]
        [NSXTProperty(IsRequired: false, Description: @"List of labels to be used for granular RBAC.Allowed in Basic edition, Essentials edition, Enterpriseedition.")]
        public IList<NSXTALBRoleFilterMatchLabelType> Markers { get; set; }
        /// <summary>
        /// WAF Rules are sorted in groups based on their
        /// characterization.
        /// Maximum of 64 items allowed.
        /// </summary>
        [JsonProperty(PropertyName = "groups")]
        [NSXTProperty(IsRequired: false, Description: @"WAF Rules are sorted in groups based on theircharacterization.Maximum of 64 items allowed.")]
        public IList<NSXTALBWafRuleGroupType> Groups { get; set; }
    }
}
