// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTIpAddressAllocationType : NSXTPolicyConfigResourceType
    {
        /// <summary>
        /// Address that is allocated from pool
        /// </summary>
        [JsonProperty(PropertyName = "allocation_ip")]
        [NSXTProperty(IsRequired: false, Description: @"Address that is allocated from pool")]
        public string? AllocationIp { get; set; }
    }
}
