// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTAggregateIPSecVpnSessionStatisticsType : NSXTAggregatePolicyRuntimeInfoType
    {
        /// <summary>
        /// List of IPSec VPN Session Statistics per Enforcement Point.
        /// </summary>
        public IList<NSXTIPSecVpnSessionStatisticsPerEPType> Results { get; set; }
    }
}
