// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Represents the Site resource information for a Span entity
        /// including both the internal id as well as the site path.
    /// </summary>
    [NSXTProperty(Description: @"Represents the Site resource information for a Span entityincluding both the internal id as well as the site path.")]
    public class NSXTSpanSiteInfoType 
    {
        /// <summary>
        /// Path of the Site resource
        /// </summary>
        public string? SitePath { get; set; }
        /// <summary>
        /// Site UUID representing the Site resource
        /// </summary>
        public string? SiteId { get; set; }
    }
}
