// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTICMPTypeServiceEntryType : NSXTServiceEntryType
    {
        public NSXTICMPTypeServiceEntryType()
        {
        }
        /// <summary>
        /// ICMP message code
        /// </summary>
        [JsonProperty(PropertyName = "icmp_code")]
        [NSXTProperty(IsRequired: false, Description: @"ICMP message code")]
        //[System.ComponentModel.DataAnnotations.MinLength(0)]
        //[System.ComponentModel.DataAnnotations.MaxLength(255)]
        public long? IcmpCode { get; set; }
        /// <summary>
        /// ICMP message type
        /// </summary>
        [JsonProperty(PropertyName = "icmp_type")]
        [NSXTProperty(IsRequired: false, Description: @"ICMP message type")]
        //[System.ComponentModel.DataAnnotations.MinLength(0)]
        //[System.ComponentModel.DataAnnotations.MaxLength(255)]
        public long? IcmpType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "protocol", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"")]
        [System.ComponentModel.DataAnnotations.Required]
        public NSXTIcmptypeServiceEntryProtocolEnumType Protocol { get; set; }
    }
}
