// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTBaseCountObservationType : NSXTCountObservationType
    {
        /// <summary>
        /// Packet count
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        [NSXTProperty(IsRequired: false, Description: @"Packet count")]
        public long? Count { get; set; }
        /// <summary>
        /// Port ID, which is either a logical port ID or an uplink name
        /// </summary>
        [JsonProperty(PropertyName = "port_id")]
        [NSXTProperty(IsRequired: false, Description: @"Port ID, which is either a logical port ID or an uplink name")]
        public string? PortId { get; set; }
        /// <summary>
        /// Type of checkpoint
        /// </summary>
        [JsonProperty(PropertyName = "checkpoint_type")]
        [NSXTProperty(IsRequired: false, Description: @"Type of checkpoint")]
        public string? CheckpointType { get; set; }
    }
}
