// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer AuthorizationPolicy object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer AuthorizationPolicy object")]
    public class NSXTALBAuthorizationPolicyType 
    {
        public NSXTALBAuthorizationPolicyType()
        {
        }
        /// <summary>
        /// Authorization Policy Rules.
        /// </summary>
        [JsonProperty(PropertyName = "authz_rules")]
        [NSXTProperty(IsRequired: false, Description: @"Authorization Policy Rules.")]
        public IList<NSXTALBAuthorizationRuleType> AuthzRules { get; set; }
    }
}
