// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTMultiWidgetConfigurationType : NSXTWidgetConfigurationType
    {
        public NSXTMultiWidgetConfigurationType()
        {
        }
        /// <summary>
        /// Array of widgets that are part of the multi-widget.
        /// </summary>
        [JsonProperty(PropertyName = "widgets", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Array of widgets that are part of the multi-widget.")]
        [System.ComponentModel.DataAnnotations.Required]
        public IList<NSXTWidgetItemType> Widgets { get; set; }
        /// <summary>
        /// Hyperlink of the specified UI page that provides details.
        /// </summary>
        [JsonProperty(PropertyName = "navigation")]
        [NSXTProperty(IsRequired: false, Description: @"Hyperlink of the specified UI page that provides details.")]
        public string? Navigation { get; set; }
    }
}
