// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Details of the member belonging to a Group
    /// </summary>
    [NSXTProperty(Description: @"Details of the member belonging to a Group")]
    public class NSXTPolicyGroupMemberDetailsType 
    {
        /// <summary>
        /// The path of the member, if relevant
        /// </summary>
        public string? Path { get; set; }
        /// <summary>
        /// The display name of the member on the enforcement point
        /// </summary>
        public string? DisplayName { get; set; }
        /// <summary>
        /// The ID of the member on the enforcement point
        /// </summary>
        public string? Id { get; set; }
    }
}
