// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTChildIpv6DadProfileType : NSXTChildPolicyConfigResourceType
    {
        /// <summary>
        /// Contains the actual Ipv6DadProfile objects
        /// </summary>
        [JsonProperty(PropertyName = "Ipv6DadProfile", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"Contains the actual Ipv6DadProfile objects")]
        [System.ComponentModel.DataAnnotations.Required]
        public NSXTIpv6DadProfileType Ipv6DadProfile { get; set; }
    }
}
