// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTRealizedEnforcementPointType : NSXTPolicyRealizedResourceType
    {
        public NSXTRealizedEnforcementPointType()
        {
        }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "realized_firewalls")]
        [NSXTProperty(IsRequired: false, Description: @"")]
        public NSXTRealizedFirewallsType RealizedFirewalls { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "realized_services")]
        [NSXTProperty(IsRequired: false, Description: @"")]
        public NSXTRealizedServicesType RealizedServices { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [JsonProperty(PropertyName = "realized_groups")]
        [NSXTProperty(IsRequired: false, Description: @"")]
        public NSXTRealizedGroupsType RealizedGroups { get; set; }
    }
}
