// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTDhcpV4StaticBindingConfigType : NSXTDhcpStaticBindingConfigType
    {
        /// <summary>
        /// When not specified, gateway address is auto-assigned from segment
        /// configuration.
        /// </summary>
        [JsonProperty(PropertyName = "gateway_address")]
        [NSXTProperty(IsRequired: false, Description: @"When not specified, gateway address is auto-assigned from segmentconfiguration.")]
        public string? GatewayAddress { get; set; }
        /// <summary>
        /// Hostname to assign to the host.
        /// </summary>
        [JsonProperty(PropertyName = "host_name")]
        [NSXTProperty(IsRequired: false, Description: @"Hostname to assign to the host.")]
        public string? HostName { get; set; }
        /// <summary>
        /// MAC address of the host.
        /// </summary>
        [JsonProperty(PropertyName = "mac_address", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"MAC address of the host.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string MacAddress { get; set; }
        /// <summary>
        /// DHCP lease time in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "lease_time")]
        [NSXTProperty(IsRequired: false, Description: @"DHCP lease time in seconds.")]
        //[System.ComponentModel.DataAnnotations.MinLength(60)]
        //[System.ComponentModel.DataAnnotations.MaxLength(4294967295)]
        [NSXTDefaultProperty(Default: "")]
        public long? LeaseTime { get; set; }
        /// <summary>
        /// IP assigned to host. The IP address must belong to the subnet, if any,
        /// configured on Segment.
        /// </summary>
        [JsonProperty(PropertyName = "ip_address", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"IP assigned to host. The IP address must belong to the subnet, if any,configured on Segment.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string IpAddress { get; set; }
        /// <summary>
        /// IPv4 DHCP options.
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        [NSXTProperty(IsRequired: false, Description: @"IPv4 DHCP options.")]
        public NSXTDhcpV4OptionsType Options { get; set; }
    }
}
