// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer AuthTacacsPlusAttributeValuePair object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer AuthTacacsPlusAttributeValuePair object")]
    public class NSXTALBAuthTacacsPlusAttributeValuePairType 
    {
        public NSXTALBAuthTacacsPlusAttributeValuePairType()
        {
        }
        /// <summary>
        /// mandatory.
        /// </summary>
        [JsonProperty(PropertyName = "mandatory")]
        [NSXTProperty(IsRequired: false, Description: @"mandatory.")]
        public bool? Mandatory { get; set; }
        /// <summary>
        /// attribute name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        [NSXTProperty(IsRequired: false, Description: @"attribute name.")]
        public string? Name { get; set; }
        /// <summary>
        /// attribute value.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        [NSXTProperty(IsRequired: false, Description: @"attribute value.")]
        public string? Value { get; set; }
    }
}
