// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTSegmentDhcpV4ConfigType : NSXTSegmentDhcpConfigType
    {
        /// <summary>
        /// IPv4 DHCP options for segment subnet.
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        [NSXTProperty(IsRequired: false, Description: @"IPv4 DHCP options for segment subnet.")]
        public NSXTDhcpV4OptionsType Options { get; set; }
    }
}
