// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer WafPSMLocationMatch object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer WafPSMLocationMatch object")]
    public class NSXTALBWafPSMLocationMatchType 
    {
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBPathMatchType Path { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBHostHdrMatchType Host { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public NSXTALBMethodMatchType Methods { get; set; }
    }
}
