// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTSegmentQoSProfileBindingMapType : NSXTQoSProfileBindingMapType
    {
        public NSXTSegmentQoSProfileBindingMapType()
        {
        }
        /// <summary>
        /// PolicyPath of associated  QoS Profile
        /// </summary>
        [JsonProperty(PropertyName = "qos_profile_path")]
        [NSXTProperty(IsRequired: false, Description: @"PolicyPath of associated  QoS Profile")]
        public string? QosProfilePath { get; set; }
    }
}
