// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Advanced load balancer HealthMonitorRadius object
    /// </summary>
    [NSXTProperty(Description: @"Advanced load balancer HealthMonitorRadius object")]
    public class NSXTALBHealthMonitorRadiusType 
    {
        /// <summary>
        /// Radius monitor will query Radius server with this username.
        /// </summary>
        [JsonProperty(PropertyName = "username", Required = Required.AllowNull)]
        public string Username { get; set; }
        /// <summary>
        /// Radius monitor will query Radius server with this password.
        /// </summary>
        public string? Password { get; set; }
        /// <summary>
        /// Radius monitor will query Radius server with this shared
        /// secret.
        /// </summary>
        public string? SharedSecret { get; set; }
    }
}
