// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTALBIpAddrGroupType : NSXTPolicyConfigResourceType
    {
        /// <summary>
        /// Configure IP address range(s).
        /// </summary>
        public IList<NSXTALBIpAddrRangeType> Ranges { get; set; }
        /// <summary>
        /// Configure IP address prefix(es).
        /// </summary>
        public IList<NSXTALBIpAddrPrefixType> Prefixes { get; set; }
        /// <summary>
        /// Configure (IP address, port) tuple(s).
        /// </summary>
        public IList<NSXTALBIpAddrPortType> IpPorts { get; set; }
        /// <summary>
        /// Populate IP addresses from tasks of this Marathon app.
        /// </summary>
        public string? MarathonAppName { get; set; }
        /// <summary>
        /// Configure IP address(es).
        /// </summary>
        public IList<NSXTALBIpAddrType> Addrs { get; set; }
        /// <summary>
        /// Populate the IP address ranges from the geo database for
        /// this country.
        /// </summary>
        public IList<string> CountryCodes { get; set; }
        /// <summary>
        /// Task port associated with marathon service port.
        /// If Marathon app has multiple service ports, this is
        /// required.
        /// Else, the first task port is used.
        /// </summary>
        public long? MarathonServicePort { get; set; }
        /// <summary>
        /// List of labels to be used for granular RBAC.
        /// Allowed in Basic edition, Essentials edition, Enterprise
        /// edition.
        /// </summary>
        public IList<NSXTALBRoleFilterMatchLabelType> Markers { get; set; }
        /// <summary>
        /// Populate IP addresses from members of this Cisco APIC EPG.
        /// </summary>
        public string? ApicEpgName { get; set; }
    }
}
