// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// IP Address and Port information
    /// </summary>
    [NSXTProperty(Description: @"IP Address and Port information")]
    public class NSXTIPAddressPortPairType 
    {
        /// <summary>
        /// The IPAddress to be combined with Port for defining specific access
        /// point.
        /// </summary>
        [JsonProperty(PropertyName = "ip_address", Required = Required.AllowNull)]
        [NSXTProperty(IsRequired: true, Description: @"The IPAddress to be combined with Port for defining specific accesspoint.")]
        [System.ComponentModel.DataAnnotations.Required]
        public string IpAddress { get; set; }
        /// <summary>
        /// The port to be combined with IPAddress for defining a specific access
        /// point.
        /// </summary>
        [JsonProperty(PropertyName = "port")]
        [NSXTProperty(IsRequired: false, Description: @"The port to be combined with IPAddress for defining a specific accesspoint.")]
        //[System.ComponentModel.DataAnnotations.MinLength(0)]
        //[System.ComponentModel.DataAnnotations.MaxLength(65535)]
        public long? Port { get; set; }
    }
}
