// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using nsxtsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.ComponentModel;
using NJsonSchema.Converters;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// 
    /// </summary>
    [NSXTProperty(Description: @"")]
    public class NSXTOspfRouteType 
    {
        /// <summary>
        /// Type to cost of the route.
        /// </summary>
        public long? TypeToCost { get; set; }
        /// <summary>
        /// Learned route prefix.
        /// </summary>
        public string? RoutePrefix { get; set; }
        /// <summary>
        /// Cost of the route.
        /// </summary>
        public long? Cost { get; set; }
        /// <summary>
        /// OSPF area.
        /// </summary>
        public string? Area { get; set; }
        /// <summary>
        /// Type of route.
        /// </summary>
        public string? RouteType { get; set; }
        /// <summary>
        /// Type of router.
        /// </summary>
        public string? RouterType { get; set; }
        /// <summary>
        /// request counter.
        /// </summary>
        public IList<NSXTOspfRouteNextHopResultType> NextHops { get; set; }
    }
}
