// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Directory domain previous sync type. It could be one of the following five states. Right after the directory domain is configured, this field is set to IDLE.
    /// </summary>
    [NSXTProperty(Description: @"Directory domain previous sync type. It could be one of the following five states. Right after the directory domain is configured, this field is set to IDLE.")]
    public enum NSXTDirectoryDomainSyncStatsPrevSyncTypeEnumType
    {
        [EnumMember(Value = "IDLE")]
        IDLE = 1,
        [EnumMember(Value = "FULL_SYNC")]
        FULLSYNC = 2,
        [EnumMember(Value = "DELTA_SYNC")]
        DELTASYNC = 3,
        [EnumMember(Value = "SELECTIVE_FULL_SYNC")]
        SELECTIVEFULLSYNC = 4,
        [EnumMember(Value = "SELECTIVE_DELTA_SYNC")]
        SELECTIVEDELTASYNC = 5,
    }
}
