// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Action enforced on the packets which matches the firewall rule.
    /// </summary>
    [NSXTProperty(Description: @"Action enforced on the packets which matches the firewall rule.")]
    public enum NSXTRealizedFirewallRuleActionEnumType
    {
        [EnumMember(Value = "ALLOW")]
        ALLOW = 1,
        [EnumMember(Value = "DROP")]
        DROP = 2,
        [EnumMember(Value = "REJECT")]
        REJECT = 3,
    }
}
