// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Indicate how IP will be allocated for the port
    /// </summary>
    [NSXTProperty(Description: @"Indicate how IP will be allocated for the port")]
    public enum NSXTPortAttachmentAllocateAddressesEnumType
    {
        [EnumMember(Value = "IP_POOL")]
        IPPOOL = 1,
        [EnumMember(Value = "MAC_POOL")]
        MACPOOL = 2,
        [EnumMember(Value = "BOTH")]
        BOTH = 3,
        [EnumMember(Value = "NONE")]
        NONE = 4,
        [EnumMember(Value = "DHCP")]
        DHCP = 5,
    }
}
