// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Group member type
    /// </summary>
    [NSXTProperty(Description: @"Group member type")]
    public enum NSXTConditionMemberTypeEnumType
    {
        [EnumMember(Value = "IPSET")]
        Ipset = 1,
        [EnumMember(Value = "VIRTUALMACHINE")]
        VirtualMachine = 2,
        [EnumMember(Value = "LOGICALPORT")]
        LogicalPort = 3,
        [EnumMember(Value = "LOGICALSWITCH")]
        LogicalSwitch = 4,
        [EnumMember(Value = "SEGMENT")]
        Segment = 5,
        [EnumMember(Value = "SEGMENTPORT")]
        SegmentPort = 6,
    }
}
