// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Admin state represents desired state of segment. It does not reflect the state of other logical entities connected/attached to the segment.
    /// </summary>
    [NSXTProperty(Description: @"Admin state represents desired state of segment. It does not reflect the state of other logical entities connected/attached to the segment.")]
    public enum NSXTSegmentAdminStateEnumType
    {
        [EnumMember(Value = "UP")]
        UP = 1,
        [EnumMember(Value = "DOWN")]
        DOWN = 2,
    }
}
