// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Valid System Health plugin types
    /// </summary>
    [NSXTProperty(Description: @"Valid System Health plugin types")]
    public enum NSXTShaPluginProfileResourceTypeEnumType
    {
        [EnumMember(Value = "PREDEFINEDPLUGIN")]
        PredefinedPlugin = 1,
        [EnumMember(Value = "DYNAMICPLUGIN")]
        DynamicPlugin = 2,
    }
}
