// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Aggregated Realization state of this object
    /// </summary>
    [NSXTProperty(Description: @"Aggregated Realization state of this object")]
    public enum NSXTConsolidatedRealizedStatusPublishStatusEnumType
    {
        [EnumMember(Value = "UNAVAILABLE")]
        UNAVAILABLE = 1,
        [EnumMember(Value = "UNREALIZED")]
        UNREALIZED = 2,
        [EnumMember(Value = "REALIZED")]
        REALIZED = 3,
        [EnumMember(Value = "ERROR")]
        ERROR = 4,
    }
}
