// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Resource type of the DNS forwarder nslookup answer.
    /// </summary>
    [NSXTProperty(Description: @"Resource type of the DNS forwarder nslookup answer.")]
    public enum NSXTPolicyDnsAnswerPerEnforcementPointResourceTypeEnumType
    {
        [EnumMember(Value = "NSXTDNSANSWER")]
        NsxTdnsAnswer = 1,
    }
}
