// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// If this field is not set for overlay segment, then the default of MTEPwill be used.
    /// </summary>
    [NSXTProperty(Description: @"If this field is not set for overlay segment, then the default of MTEPwill be used.")]
    public enum NSXTSegmentReplicationModeEnumType
    {
        [EnumMember(Value = "MTEP")]
        MTEP = 1,
        [EnumMember(Value = "SOURCE")]
        SOURCE = 2,
    }
}
