// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// The status of the traceflow RPC request. SUCCESS - The traceflow request is sent successfully. TIMEOUT - The traceflow request gets timeout. SOURCE_PORT_NOT_FOUND - The source port of the request cannot be found. DATA_PATH_NOT_READY - The datapath component cannot be ready to receive request. CONNECTION_ERROR - There is connection error on datapath component. UNKNOWN - The status of traceflow request cannot be determined.
    /// </summary>
    [NSXTProperty(Description: @"The status of the traceflow RPC request. SUCCESS - The traceflow request is sent successfully. TIMEOUT - The traceflow request gets timeout. SOURCE_PORT_NOT_FOUND - The source port of the request cannot be found. DATA_PATH_NOT_READY - The datapath component cannot be ready to receive request. CONNECTION_ERROR - There is connection error on datapath component. UNKNOWN - The status of traceflow request cannot be determined.")]
    public enum NSXTTraceflowRequestStatusEnumType
    {
        [EnumMember(Value = "SUCCESS")]
        SUCCESS = 1,
        [EnumMember(Value = "TIMEOUT")]
        TIMEOUT = 2,
        [EnumMember(Value = "SOURCE_PORT_NOT_FOUND")]
        SOURCEPORTNOTFOUND = 3,
        [EnumMember(Value = "DATA_PATH_NOT_READY")]
        DATAPATHNOTREADY = 4,
        [EnumMember(Value = "CONNECTION_ERROR")]
        CONNECTIONERROR = 5,
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 6,
    }
}
