// <auto-generated>
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System.Runtime.Serialization;
using nsxtsdk.Models;

namespace nsxtsdk.PolicyModels
{
    /// <summary>
    /// Type of the infrastructure.
    /// </summary>
    [NSXTProperty(Description: @"Type of the infrastructure.")]
    public enum NSXTContainerInfrastructureInfoInfraTypeEnumType
    {
        [EnumMember(Value = "VSPHERE")]
        VSphere = 1,
        [EnumMember(Value = "AWS")]
        AWS = 2,
        [EnumMember(Value = "AZURE")]
        Azure = 3,
        [EnumMember(Value = "VMC")]
        VMC = 4,
        [EnumMember(Value = "KVM")]
        KVM = 5,
        [EnumMember(Value = "BAREMETAL")]
        Baremetal = 6,
    }
}
